w4d4/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new] do
    resources :notes, only: [:index]
  end

  resources :notes, only: [:edit, :destroy, :update, :create]
end

w4d4/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  band_id    :integer          not null
#  name       :text             not null
#  edition    :text             not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  belongs_to :band

  has_many :tracks, dependent: :destroy

  validates :band_id, presence: true
  validates :name, presence: true
  validates :edition, inclusion: ['live', 'studio']

  delegate :name, to: :band, prefix: true

  def num_tracks
    self.tracks.count
  end
end

w4d4/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :check_logged_in
  before_action :get_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def show
  end

  def edit
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    if @album.save
      flash[:success] = ['Album created']
      redirect_to album_url(@album)
    else
      flash.now[:danger] = @album.errors.full_messages
      render :new
    end
  end

  def update
    if @album.update(band_params)
      flash[:success] = ['Album updated']
      redirect_to album_url(@album)
    else
      flash.now[:danger] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @album.destroy
      flash[:success] = ['Album deleted']
      redirect_to band_url(@album.band)
    else
      flash.now[:danger] = @album.errors.full_messages
      render :show
    end
  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :edition)
  end

  def get_album
    @album = Album.find_by(id: params[:id])
  end
end

w4d4/app/helpers/albums_helper.rb
module AlbumsHelper
end

w4d4/app/views/albums/_form.html.erb
<% url = action == :new ? albums_url : album_url(album) %>
<% http = action == :new ? :post : :patch %>

<div class="col-lg-6 col-lg-offset-3">
  <h3><%= action.capitalize %> Album </h3>

  <form action="<%= url %>" method="post">
    <input type="hidden" name="_method" value="<%= http %>">
    <%= auth_token %>

    <div class="form-group row">
      <label for="name">Name: </label>
      <input id='name' class='form-control' type="text" name="album[name]" value="<%= album.name %>">
    </div>

    <div class="form-group row">
      <label for="band">Band: </label>
      <select id='band' class="" name="album[band_id]">
        <option disabled selected>--Select the band---</option>
        <% Band.all.each do |band| %>
          <option value="<%= band.id %>" <%= 'selected' if band.id == album.band_id %>><%= band.name %></option>
        <% end %>
      </select>
    </div>

    <div class="form-group row">
      <input type="radio" name="album[edition]" value="studio" <%= 'checked' if album.edition == 'studio' %>> Studio
      &nbsp&nbsp&nbsp
      <input type="radio" name="album[edition]" value="live" <%= 'checked' if album.edition == 'live' %>> Live
    </div>

    <div class="form-group row">
      <input class='btn btn-success' type="submit" value="<%= action.capitalize %> Album">
    </div>
  </form>
</div>

w4d4/app/views/albums/edit.html.erb
<%= render 'form', album: @album, action: :edit %>

w4d4/app/views/albums/index.html.erb
<h3>All Albums</h3>

<hr>

<ul class="list-group">
  <% @albums.each do |album| %>
    <a href='<%= album_url(album) %>' class="list-group-item">
      <%= album.name %>
    </a>
  <% end %>
</ul>


<%= link_to 'Add Album', new_band_album_url(1), class: 'btn btn-success' %>

w4d4/app/views/albums/new.html.erb
<%= render 'form', album: @album, action: :new %>

w4d4/app/views/albums/show.html.erb
<h2>'<%= @album.name %>' <small>Album Page</small> </h2>
<hr>

<h4> Band:
<%= link_to @album.band_name, band_url(@album.band), class: 'label label-primary' %>
</h4>

<ul class="list-group">

  <% @album.tracks.each_with_index do |track, idx| %>
    <a href="<%= track_url(track) %>" class="list-group-item">
      Track<%= idx + 1 %>: &nbsp&nbsp&nbsp&nbsp&nbsp<%= track.name %>
    </a>
  <% end %>

</ul>

<%= link_to 'Add Track', new_album_track_url(params[:id]), class:'btn btn-success' %>
<br>
<br>
<%= button_to 'Delete Album', album_url(@album), method: :delete, class: 'btn btn-danger' %>