w4d4/config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:new] do
    resources :tracks, only: [:new]
  end

  resources :tracks, except: [:new] do
    resources :notes, only: [:index]
  end

  resources :notes, only: [:edit, :destroy, :update, :create]
end

w4d4/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ActiveRecord::Base
  has_many :albums, dependent: :destroy
  has_many :tracks, through: :albums, source: :tracks
  validates :name, presence: true, uniqueness: true

  def num_albums
    self.albums.count
  end
end

w4d4/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action :check_logged_in
  before_action :get_band, only: [:show, :edit, :update, :destroy]

  def index
    @bands = Band.all
  end

  def show
    session[:return_to] ||= band_url(@band)
  end

  def new
    @band = Band.new
  end

  def create
    @band = Band.new(band_params)
    if @band.save
      flash[:success] = ['Band created']
      redirect_to band_url(@band)
    else
      flash.now[:danger] = @band.errors.full_messages
      render :new
    end
  end

  def edit
  end

  def update
    if @band.update(band_params)
      flash[:success] = ['Band updated']
      redirect_to band_url(@band)
    else
      flash.now[:danger] = @band.errors.full_messages
      render :edit
    end
  end

  def destroy
    if @band.destroy
      flash[:success] = ['Band deleted']
      redirect_to bands_url
    else
      flash.now[:danger] = @band.errors.full_messages
    end
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end

  def get_band
    @band = Band.find_by(id: params[:id])
  end


end

w4d4/app/helpers/bands_helper.rb
module BandsHelper
end

w4d4/app/views/bands/_form.html.erb
<% url = action == :new ? bands_url : band_url(band) %>
<% http = action == :new ? :post : :patch %>

<div class="col-lg-6 col-lg-offset-3">
  <h3><%= action.capitalize %> Band </h3>

  <form action="<%= url %>" method="post">
    <input type="hidden" name="_method" value="<%= http %>">
    <%= auth_token %>

    <div class="form-group row">
      <label for="name">name: </label>
      <input id='name' class='form-control' type="text" name="band[name]" value="<%= band.name %>">
    </div>

    <div class="form-group row">
      <input class='btn btn-success' type="submit" value="<%= action.capitalize %> Band">
    </div>
  </form>
</div>

w4d4/app/views/bands/edit.html.erb
<%= render 'form', band: @band, action: :edit %>

w4d4/app/views/bands/index.html.erb
<h3>All Bands</h3>

<hr>

<ul class="list-group">
  <% @bands.each do |band| %>
    <a href='<%= band_url(band) %>' class="list-group-item">
      <span class="badge"><%= pluralize(band.num_albums, 'album') %></span>
      <%= band.name %>
    </a>
  <% end %>
</ul>


<%= link_to 'Add Band', new_band_url, class: 'btn btn-success' %>

w4d4/app/views/bands/new.html.erb
<%= render 'form', band: @band, action: :new %>

w4d4/app/views/bands/show.html.erb
<h2>'<%= @band.name %>' <small>Band Page</small> </h2>
<hr>

<ul class="list-group">

  <% @band.albums.each do |album| %>
    <a href="<%= album_url(album) %>" class="list-group-item">
      <span class="badge"><%= album.tracks.count %></span>
      <%= album.name %>
    </a>
  <% end %>
</ul>

<%= link_to 'Add Album', new_band_album_url(@band.id), class: 'btn btn-success' %>
<br>
<br>
<%= link_to 'Edit Band', edit_band_url(@band), class: 'btn btn-success' %>
<br>
<br>
<%= button_to 'Delete Band', band_url(@band), method: :delete, class: 'btn btn-danger' %>